version: 2
jobs:
  # branches:
  #   only:
  #     - feature/circleCI
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.2-apache-stretch-node-browsers
    steps:
      - checkout
      # - ls
      # - pwd
      # - scp script/start.sh
      # - scp sourceCode
      # - ssh SERVER_IP 'sh start.sh'
      - run: echo "test and ok"
      # - run: echo $SERVER_IP